# GitHub Actions Workflow
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions

name: CI Testing for XSLT Files

on:   # yamllint disable-line rule:truthy
  pull_request:
    branches-ignore:
    - template
    paths:
    - '**/*.xsl'
    - '**/*.xslt'
  push:
    branches-ignore:
    - template
    paths:
    - '**/*.xsl'
    - '**/*.xslt'
    - .github/workflows/ci-xslt.yml
  schedule:
  # Run once a month (at 8:40 AM UTC) to check for exogenous breakage.
  - cron: '40 8 2 * *'
  workflow_dispatch: {}

permissions: {}

jobs:
  test:
    name: Lint, Validate, and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        persist-credentials: false

    - name: Install npm test dependencies
      run: |
        # allow-git was added in npm 11, which is not currently in ubuntu-latest
        # https://github.blog/changelog/2026-02-18-npm-bulk-trusted-publishing-config-and-script-security-now-generally-available/
        npm config set allow-git=none || true
        npm config set ignore-scripts=true
        npm install --strict-peer-deps

    - name: Install apt test dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends \
          jing \
          libsaxon-java \
          libxml2-utils \
          trang \
          xalan \
          xsltproc

    - name: Lint with xslint
      # Note: xslint/xslint-action just calls xslint via npx
      # https://github.com/xslint/xslint-action/blob/0.0.9/index.js#L23
      # Do so directly for simplicity, version control, and to avoid a dep.
      run: npx @maxonfjvipon/xslint --max-warnings=0

    - name: Schema validate XSLT files
      run: |
        find . \( -iname '*.xsl' -o -iname '*.xslt' \) -print0 |
          xargs -0r -L 1 ./test/validate-xslt.sh

    - name: Golden Master Testing
      run: |
        # Generate fresh outputs in different directory.
        # Could overwrite and git-diff(1), but must be careful of ctime/mtime.
        outdir=$(mktemp -dt)
        gmake -C test -j OUTDIR="$outdir"
        echo 'Differences from expected output:'
        diff -Nru test/outputs "$outdir"

    - name: Check formatting with prettier
      run: |
        # Use --write followed by git-diff(1) to produce a diff
        # See https://github.com/prettier/prettier/issues/6885
        npx prettier --write '**/*.{xsl,xslt}'
        git diff --exit-code
